package whatsapp

// Selectors maps UI element names to their CSS/XPath selectors used by WhatsApp Web.
var Selectors = map[string][]string{
	"dismiss_popup": {
		`div[role="dialog"] button`,
		`[data-animate-modal-popup="true"] button`,
		`[data-animate-modal-backdrop="true"] button`,
		`div[role="alertdialog"] button`,
		`span[data-icon="x"]`,
		`button[aria-label="关闭"]`,
		`button[aria-label="Close"]`,
		`button[aria-label="好的"]`,
		`button[aria-label="确定"]`,
		`button[aria-label="OK"]`,
	},
	"invalid_phone_popup": {
		`//*[(@role="dialog" or @role="alertdialog") and (contains(., "未注册") or contains(., "无效") or contains(., "不是有效") or contains(., "无法使用") or contains(., "not registered") or contains(., "not valid") or contains(., "invalid"))]`,
		`//*[contains(., "Phone number shared via url is invalid")]`,
		`//*[contains(., "The phone number shared via url is invalid")]`,
	},
	"chat_input": {
		`div[contenteditable="true"][data-tab="10"]`,
		`footer div[contenteditable="true"]`,
		`div[contenteditable="true"][title="输入消息"]`,
		`div[contenteditable="true"][title="Type a message"]`,
		`div[contenteditable="true"][data-placeholder]`,
		`div[contenteditable="true"][aria-placeholder]`,
	},
	"logged_in": {
		`#side`,
		`[data-testid="chat-list"]`,
		`div[aria-label="Chat list"]`,
		`div[aria-label="聊天列表"]`,
		`div[role="grid"][aria-label="Chat list"]`,
		`div[role="grid"][aria-label="聊天列表"]`,
		`div[contenteditable="true"][data-tab="3"]`,
		`div[contenteditable="true"][title="搜索或开始新对话"]`,
		`div[contenteditable="true"][title="Search input textbox"]`,
	},
	"send_button": {
		`span[data-icon="wds-ic-send-filled"]`,
		`footer button[data-tab="11"]`,
		`button[data-tab="11"]`,
		`span[data-icon="send"]`,
		`span[data-icon="send-v2"]`,
		`div[aria-label="Send"]`,
		`button[aria-label="Send"]`,
		`[data-icon="send"]`,
	},
	"attach_button": {
		`span[data-icon="plus-rounded"]`,
		`span[data-icon="clip"]`,
		`[aria-label="Attach"]`,
		`span[data-icon="plus"]`,
		`span[data-icon="plus-filled"]`,
		`[data-icon="plus"]`,
		`[data-testid="attach-menu-btn"]`,
		`#main footer [data-icon="plus"]`,
	},
	"attach_image_option": {
		`span[data-testid="attach-image"]`,
		`input[accept="image/*,video/mp4,video/3gpp,video/quicktime"]`,
		`input[accept*="image"]`,
		`[aria-label="Photos & videos"]`,
		`span[data-icon="image"]`,
	},
	"attach_document_option": {
		`//span[normalize-space()='文档']/ancestor::*[@role='button' or self::button or self::li or @tabindex][1]`,
		`//li[.//span[normalize-space()='文档']]`,
		`//div[normalize-space()='文档']/ancestor::*[@role='button' or self::button or self::li or @tabindex][1]`,
		`//span[normalize-space()='文档']`,
		`//span[normalize-space()='Document']/ancestor::*[@role='button' or self::button or self::li or @tabindex][1]`,
		`//li[.//span[normalize-space()='Document']]`,
		`//div[normalize-space()='Document']/ancestor::*[@role='button' or self::button or self::li or @tabindex][1]`,
		`//span[normalize-space()='Document']`,
		`//span[text()='Document']`,
		`//div[@role='application']/ul//span[text()='Document']`,
		`span[data-testid="attach-document"]`,
		`span[data-icon="doc"]`,
		`[aria-label="Document"]`,
	},
	"preview_send": {
		`span[data-icon="wds-ic-send-filled"]`,
		`span[data-icon="send"]`,
		`span[data-icon="send-v2"]`,
		`div[aria-label="Send"]`,
		`button[aria-label="Send"]`,
		`[data-icon="send"]`,
	},
}
