// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {whatsapp} from '../models';

export function GeoCities(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GeoCountries():Promise<Array<Record<string, any>>>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFileDialogForAttachment(arg1:string,arg2:number):Promise<void>;

export function OpenFileDialogForCSV():Promise<void>;

export function Ping():Promise<string>;

export function PollCSVResult():Promise<Record<string, any>>;

export function PollFileResult():Promise<Record<string, any>>;

export function ResultsCategories(arg1:main.ResultFilter):Promise<Array<string>>;

export function ResultsImportToWhatsApp(arg1:main.ResultFilter):Promise<Record<string, any>>;

export function ResultsSearch(arg1:main.ResultFilter):Promise<Array<main.BusinessResult>>;

export function ScraperCancelJob(arg1:string):Promise<Record<string, any>>;

export function ScraperDeleteJob(arg1:string):Promise<Record<string, any>>;

export function ScraperListJobs():Promise<Array<Record<string, any>>>;

export function ScraperStartJob(arg1:main.ScraperStartRequest):Promise<Record<string, any>>;

export function SettingsCheckEnvironment():Promise<Record<string, any>>;

export function SettingsImportCitiesDB(arg1:string):Promise<Record<string, any>>;

export function SettingsInstallBrowsers():Promise<void>;

export function SettingsSelectCitiesDB():Promise<Record<string, any>>;

export function WhatsAppListContacts():Promise<Record<string, any>>;

export function WhatsAppLoginStart():Promise<Record<string, any>>;

export function WhatsAppLoginStatus():Promise<Record<string, any>>;

export function WhatsAppLogout():Promise<void>;

export function WhatsAppSelectContactsFile():Promise<Record<string, any>>;

export function WhatsAppSend(arg1:Array<string>,arg2:Array<whatsapp.Message>,arg3:whatsapp.SendOptions):Promise<void>;

export function WhatsAppStop():Promise<void>;

export function WhatsAppUploadContacts(arg1:Array<number>):Promise<Record<string, any>>;

export function WhatsAppUploadContactsFile(arg1:string):Promise<Record<string, any>>;
