// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeoCities(arg1, arg2) {
  return window['go']['main']['App']['GeoCities'](arg1, arg2);
}

export function GeoCountries() {
  return window['go']['main']['App']['GeoCountries']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenFileDialogForAttachment(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialogForAttachment'](arg1, arg2);
}

export function OpenFileDialogForCSV() {
  return window['go']['main']['App']['OpenFileDialogForCSV']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PollCSVResult() {
  return window['go']['main']['App']['PollCSVResult']();
}

export function PollFileResult() {
  return window['go']['main']['App']['PollFileResult']();
}

export function ResultsCategories(arg1) {
  return window['go']['main']['App']['ResultsCategories'](arg1);
}

export function ResultsImportToWhatsApp(arg1) {
  return window['go']['main']['App']['ResultsImportToWhatsApp'](arg1);
}

export function ResultsSearch(arg1) {
  return window['go']['main']['App']['ResultsSearch'](arg1);
}

export function ScraperCancelJob(arg1) {
  return window['go']['main']['App']['ScraperCancelJob'](arg1);
}

export function ScraperDeleteJob(arg1) {
  return window['go']['main']['App']['ScraperDeleteJob'](arg1);
}

export function ScraperListJobs() {
  return window['go']['main']['App']['ScraperListJobs']();
}

export function ScraperStartJob(arg1) {
  return window['go']['main']['App']['ScraperStartJob'](arg1);
}

export function SettingsCheckEnvironment() {
  return window['go']['main']['App']['SettingsCheckEnvironment']();
}

export function SettingsImportCitiesDB(arg1) {
  return window['go']['main']['App']['SettingsImportCitiesDB'](arg1);
}

export function SettingsInstallBrowsers() {
  return window['go']['main']['App']['SettingsInstallBrowsers']();
}

export function SettingsSelectCitiesDB() {
  return window['go']['main']['App']['SettingsSelectCitiesDB']();
}

export function WhatsAppListContacts() {
  return window['go']['main']['App']['WhatsAppListContacts']();
}

export function WhatsAppLoginStart() {
  return window['go']['main']['App']['WhatsAppLoginStart']();
}

export function WhatsAppLoginStatus() {
  return window['go']['main']['App']['WhatsAppLoginStatus']();
}

export function WhatsAppLogout() {
  return window['go']['main']['App']['WhatsAppLogout']();
}

export function WhatsAppSelectContactsFile() {
  return window['go']['main']['App']['WhatsAppSelectContactsFile']();
}

export function WhatsAppSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['WhatsAppSend'](arg1, arg2, arg3);
}

export function WhatsAppStop() {
  return window['go']['main']['App']['WhatsAppStop']();
}

export function WhatsAppUploadContacts(arg1) {
  return window['go']['main']['App']['WhatsAppUploadContacts'](arg1);
}

export function WhatsAppUploadContactsFile(arg1) {
  return window['go']['main']['App']['WhatsAppUploadContactsFile'](arg1);
}
